cApp/urls.py
from django.urls import path

from . import views

app_name = 'cApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('n2w/', views.n2w, name='n2w'),
    path('w2n/', views.w2n, name='w2n'),
]

converter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cApp.urls')),
]

cApp/models.py
from django.db import models

# Create your models here.

cApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from .utils import n2w as n2w_util, w2n as w2n_util


def index(request):
    return render(request, 'index.html')


def n2w(request):
    num = request.POST.get('number', None)
    if num:
        if len(str(num)) > 12:
            return HttpResponse({"Please enter less than billion!"}, content_type='application/json', status=406)
        num = num.replace('.', '').replace(',', '')
        res = n2w_util.get_number_as_words(int(num))
        return JsonResponse({'res': res})
    else:
        return HttpResponseBadRequest()


def w2n(request):
    words = request.POST.get('text', None)
    if words:
        words = words.replace(' and ', ' ').replace('-', ' ').lower()
        try:
            res = w2n_util.get_words_as_number(words)
            return JsonResponse({'res': res})
        except Exception as e:
            return HttpResponse(e, content_type='application/json', status=406)
    else:
        return HttpResponseBadRequest()

cApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Trendyol Case Study</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<div class="page-header">
    <h3 style="color: darkblue;
                text-align: center;
                padding: 15px;
                margin: 5px;
                border-bottom: lightskyblue 2px solid">
        Number2Word / Word2Number Converter
    </h3>
</div>
<div class="content">

    <div class="container mt-5">

    {% block content %}
    {% endblock %}

    </div>

</div>

<footer class="footer" style="text-align: center;
                        font-size: small;
                        border-top: lightskyblue 1px solid;
                        position: absolute;
                        bottom: 0;
                        width: 100%;">

  <div class="container">
    <span class="text-muted">Made by Batuhan Demir for <a href="//trendyol.com">trendyol.com</a> </span>
  </div>

</footer>

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

cApp/templates/index.html
{% extends "base.html" %}

{% block content %}
{% csrf_token %}


<div class="row mb-5">
    <div class="col">
        <p>
        <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#data-info" aria-expanded="false" aria-controls="info">
            How does the tool work?
        </button>
    </p>
    <div class="collapse" id="data-info">
        <div class="card card-body bg-light text-info">
            This tool has ability to convert any integer to its corresponding string of words and
            to convert string of words to number<br>
            -> Only numbers up to billion are converted to words!<br>
            -> Please enter valid number words, only correct ones are converted to number!
        </div>
    </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col" style="margin-top: -25px">
        <div class="input-group mb-3">
            <input class="rounded" id="n2w-input" style="width: 200px;" type="number" placeholder="Enter a number"  >
            <div class="input-group-append">
                <button class="btn btn-outline-primary" type="button" id="n2w-button">Convert to Words</button>
            </div>
        </div>
        <div  class="alert alert-success" role="alert" id="n2w-res-success" style="display: none;">
            <b><i>Result:</i> </b> <span></span>
        </div>
        <div class="alert alert-danger" role="alert" id="n2w-res-error" style="display: none;">
            <b><i>Error:</i> </b> <span></span>
        </div>
    </div>

    <div class="col" style="margin-top: -25px">
        <div class="input-group mb-3">
            <textarea class="rounded" id="w2n-input" style="width: 350px; height: 100px;"  placeholder="Enter words" ></textarea>
            <div class="input-group-append">
                <button class="btn btn-outline-primary" type="button" id="w2n-button">Convert to Number</button>
            </div>
        </div>
        <div class="alert alert-success" role="alert" id="w2n-res-success" style="display: none;">
            <b><i>Result:</i> </b> <span></span>
        </div>
        <div class="alert alert-danger" role="alert" id="w2n-res-error" style="display: none;">
            <b><i>Error:</i> </b> <span></span>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        $ =  jQuery;
        let csrf = $('input[name="csrfmiddlewaretoken"]').val();

        $("#n2w-button").click(() => {
            let val = $('#n2w-input').val();
            if (val){
                $.ajax({
                    url: '{% url "cApp:n2w" %}',
                    data: { 'number' : val, 'csrfmiddlewaretoken' : csrf },
                    dataType: 'json',
                    method: 'POST',
                    success: (data) => {
                        $("#n2w-res-success span").text(data['res']);
                        $("#n2w-res-success").show();
                        $("#n2w-res-error").hide();
                    },
                    error: (err) => {
                        console.log(err.responseText);
                        $("#n2w-res-error span").text(err.responseText);
                        $("#n2w-res-error").show();
                        $("#n2w-res-success").hide();
                    }
                });
            }
        });

        $("#w2n-button").click(() => {
            let val = $('#w2n-input').val();
            if (val){
                $.ajax({
                    url: '{% url "cApp:w2n" %}',
                    data: { 'text' : val, 'csrfmiddlewaretoken' : csrf },
                    dataType: 'json',
                    method: 'POST',
                    success: (data) => {
                        $("#w2n-res-success span").text(data['res']);
                        $("#w2n-res-success").show();
                        $("#w2n-res-error").hide();
                    },
                    error: (err) => {
                        console.log(err.responseText);
                        $("#w2n-res-error span").text(err.responseText);
                        $("#w2n-res-error").show();
                        $("#w2n-res-success").hide();
                    }
                });
            }
        });
    })
</script>

{% endblock %}